### ISSUE TITLE
StoreAdmin Dashboard: Crear, Editar, Eliminar Item

### ISSUE THREAD

**Issue by krarrobo1** [peramon/System_SGI#2]
**TODO List**

- [x] Crear formulario y servicio para ingresar un item nuevo
- [x] Crear formulario y servicio para editar un item
- [x]  Eliminar store_items del detalle

**Comment by peramon** [comment]
Nel
